services:
  dns-server:
    image: ubuntu/bind9
    container_name: dns-server
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/db.lab.local:/etc/bind/db.lab.local
    networks:
      lan:
        ipv4_address: 172.29.1.2

  debian1:
    build: ./ansible/debian1
    container_name: debian1
    networks:
      lan:
        ipv4_address: 172.29.1.10

  debian2:
    image: debian
    container_name: debian2
    command: sleep infinity
    tty: true
    networks:
      lan:
        ipv4_address: 172.29.1.20

  webserver:
    image: httpd
    container_name: webserver
    volumes:
      - ./apache/index.html:/usr/local/apache2/htdocs/index.html
    networks:
      lan:
        ipv4_address: 172.29.1.30

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      lan:
        ipv4_address: 172.29.1.3

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
